matter_server: Bump Python Matter server to 5.7.0
Bump the Python Matter server to 5.7.0. Also add Matter SDK log level as
separate (optional) configuration. This allows to select the Matter SDK
log level separately from the server logging level.

diff --git a/matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run b/matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run
--- a/matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run
+++ b/matter_server/rootfs/etc/s6-overlay/s6-rc.d/matter-server/run
@@ -6,14 +6,17 @@ bashio::log.info "Starting Matter Server..."
 
 declare server_port
 declare log_level
+declare log_level_sdk
 declare primary_interface
 extra_args=()
 
-log_level=$(bashio::string.lower "$(bashio::config log_level invalid)")
-if [ "$log_level" = "invalid" ]; then
-  bashio::log.magenta 'Received invalid log_level from config, fallback to info'
-  log_level="info"
+if ! bashio::config.exists log_level; then
+  bashio::log.magenta 'No log_level set in config, fallback to info'
 fi
+log_level=$(bashio::string.lower "$(bashio::config log_level info)")
+
+# Make Matter SDK log level currently default to error
+log_level_sdk=$(bashio::string.lower "$(bashio::config log_level_sdk error)")
 
 if bashio::config.true "beta"; then
     bashio::log.info 'Upgrading Python Matter Server to latest pre-release'
@@ -45,6 +48,7 @@ if bashio::config.true "beta"; then
                        --fabricid 2 --vendorid 4939 "${extra_args[@]}"
 else
     exec /usr/local/bin/matter-server --storage-path "/data" --port "${server_port}" \
-                       --log-level "${log_level}" --primary-interface "${primary_interface}" \
+                       --log-level "${log_level}" --log-level-sdk "${log_level_sdk}" \
+                       --primary-interface "${primary_interface}" \
                        --fabricid 2 --vendorid 4939 "${extra_args[@]}"
 fi
